mysql_image: 'mysql'
mysql_tag: '5.7'

elastic_image: 'elasticsearch'
elastic_tag: '7.13.2'

magento2_image: ''
magento2_tag: ''

magento2_url: ''

github_api_token: ''
gitlab_api_token: ''
mage_account_public_key: ''
mage_account_private_key: ''

hipay_api_user_test: ''
hipay_api_password_test: ''
hipay_secret_passphrase_test: ''
hipay_tokenjs_username_test: ''
hipay_tokenjs_publickey_test: ''
hipay_applepay_username_test: ''
hipay_applepay_password_test: ''
hipay_applepay_secret_passphrase_test: ''
hipay_applepay_tokenjs_username_test: ''
hipay_applepay_tokenjs_publickey_test: ''

pi_data_url: ''
